from agents.random_mario import RandomMarioAgent
from agents.random_pokemon import RandomPokemonAgent
from agents.random_twenty_fourty_eight import RandomTwentyFourtyEightAgent
from agents.random_starcraft import RandomStarCraftAgent

PokemonAgent = RandomPokemonAgent
TwentyFourtyEightAgent = RandomTwentyFourtyEightAgent
SuperMarioAgent = RandomMarioAgent
StarCraftAgent = RandomStarCraftAgent
